### ISSUE TITLE
TODO comment left in `AccountCreateTransaction`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-swift#12]
There is a TODO comment left in the AccountCreateTransaction code. Not sure if there is something left here or if it should be removed. https://github.com/hashgraph/hedera-sdk-swift/blob/main/Sources/Hedera/AccountCreateTransaction.swift#L39

Additional TODO comments:

- https://github.com/hashgraph/hedera-sdk-swift/blob/main/Sources/Hedera/AccountInfo.swift#L3
- https://github.com/hashgraph/hedera-sdk-swift/blob/main/Sources/Hedera/AccountInfo.swift#L26

**Comment by mehcode** [comment]
Fixed in https://github.com/hashgraph/hedera-sdk-rust/pull/204
