### ISSUE TITLE
Getting Compile time error after adding dependancy

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#127]
### Description

Added dependancy in new project getting compile time errors.

**Command SwiftCompile failed with a nonzero exit code**

Attached screenshot for errors and SDK version used

<img width="301" alt="Screenshot 2023-06-27 at 6 10 36 PM" src="https://github.com/hashgraph/hedera-sdk-swift/assets/10366353/3cdd2ad9-232a-4dd9-a249-d17066ac9ac4">

### Steps to reproduce

Create new iOS project
Add Hedera Swift SDK dependancy
Build Project

### Additional context

<img width="502" alt="Screenshot 2023-06-27 at 6 08 21 PM" src="https://github.com/hashgraph/hedera-sdk-swift/assets/10366353/35b7c3ff-dd34-4450-bc6f-99c228a0170b">

### Hedera network

testnet

### Version

v0.21.0

### Operating system

macOS

**Comment by izik1** [comment]
Hi! It seems that a dependency is being resolved through breaking changes 😅

This will be properly resolved in the next version, however here is a temporary workaround:

1. add `.package(url: "https://github.com/GigaBitcoin/secp256k1.swift.git", .upToNextMinor(from: "0.10")),` to your package dependencies (this is the dependency in question)
2. Build the package
3. Remove the line added earlier

this forces swift to use the correct version of the dependency
As stated, this will be properly resolved in v0.22.0
