### ISSUE TITLE
`deleteAccountId` should be `accountId` for `AccountDeleteTransaction`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-swift#14]
Swift: https://github.com/hashgraph/hedera-sdk-swift/blob/main/Sources/Hedera/AccountDeleteTransaction.swift#L28

Java: https://github.com/hashgraph/hedera-sdk-java/blob/main/sdk/src/main/java/com/hedera/hashgraph/sdk/AccountDeleteTransaction.java#L90

Should be  `accountId(_deleteAccountId: AccountId)` instead of `deleteAccountId(_ deleteAccountId: AccountId)`

**Comment by mehcode** [comment]
Fixed in https://github.com/hashgraph/hedera-sdk-rust/pull/204
