### ISSUE TITLE
Unable to get Raw transaction from TransferTransaction object

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#199]
### Description

Trying to fetched details of TransferTransaction before executing but some methods are private so unable to access the information about the transaction like tokenTransfers and how to print raw transaction.

### Steps to reproduce

Create an object of TransferTransaction
Try to access information before execution it.
Unable to fetch details of TokenTransfers

### Hedera network

testnet

### Version

v0.23.0

### Operating system

macOS

**Comment by izik1** [comment]
Hi! I can see that getters for `tokenTransfers` and `tokenNftTransfers` are indeed missing from `TransferTransaction`.

However, I'm not sure what you mean by "print raw transaction"

**Comment by nirmalpatidar123** [comment]
@izik1 Yes the getter method is missing, Also I need to get Raw transaction from any Transaction object.

**Comment by izik1** [comment]
I added the getters... But I still don't know what you mean by "raw transaction"

**Comment by nirmalpatidar123** [comment]
> I added the getters... But I still don't know what you mean by "raw transaction"

I need the json string for any transaction with all the details.

**Comment by nirmalpatidar123** [comment]
Hi @izik1 Thanks for the getters methods for tokenTransfers and tokenNftTransfers .
