### ISSUE TITLE
Unable to get list of signature map used for signing the transaction

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#205]
### Description

In Transaction class in Java SDK we have a method get list of sigPairLists but similar method not exist for Swift SDK. 
How to get list of signatures used for signing the transaction.

### Steps to reproduce

Create an signed transaction and try to get public keys used for signing that transaction.

### Hedera network

mainnet

### Version

v0.23.0

### Operating system

macOS

**Comment by izik1** [comment]
Are you referring to `getSignature`? (https://github.com/hashgraph/hedera-sdk-java/blob/0d0da85dcea114140c92a2fba2d8cf08f1ed3b81/sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java#L948)

**Comment by nirmalpatidar123** [comment]
Yes
