### ISSUE TITLE
'NumberKit' requires minimum platform version 12.0

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-swift#21]
### Description

The following error occurred when adding the sdk to a simple project

`The package product 'NumberKit' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0`

### Steps to reproduce

created a simple iOS project
added Hedera package
Clicked run

### Hedera network

testnet

### Version

beta

**Comment by mehcode** [comment]
This is not a bug and is by intention. iOS versions before 13 are officially discontinued by Apple and should neither be used nor developed for.

Please update the minimum platform version in your project.

**Comment by valeraOlexienko** [comment]
It does not help if you set the minimum platform version on the project level.
I have the exact same issue as @gregscullard mentioned.
