### ISSUE TITLE
Swift tools version specification is missing

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-sdk-swift#23]
### Description

Xcode reports when trying to build:

`the Swift tools version specification is missing a label; consider inserting 'swift-tools-version:' between the comment marker and the version specifier`

In [Package.swift](https://github.com/hashgraph/hedera-sdk-swift/blob/main/Package.swift), the following line should be moved a the top (before source code header):

`// swift-tools-version:5.5`

### Steps to reproduce

1) Clone git@github.com:hashgraph/hedera-sdk-swift.git
2) Open hedera-sdk-swift with Xcode 13.4.1
3) Build
    => build fails with the following message:

`the Swift tools version specification is missing a label; consider inserting 'swift-tools-version:' between the comment marker and the version specifier`

### Hedera network

testnet

### Version

0.5.0

### Operating system

macOS

**Comment by mehcode** [comment]
I see what happened. When this repo was made public, an automated tool added the license headers. 

Fixed: https://github.com/hashgraph/hedera-sdk-rust/pull/204

**Comment by ericleponner** [comment]
Issue has been closed but error in Package.swift is always present.
Did I miss something ?

**Comment by mehcode** [comment]
@ericleponner I fixed the issue in the linked PR but we can't release the package until another member of the team is online to merge the PR. Watch the linked PR above. Few other fixes in there as well.

**Comment by ericleponner** [comment]
Ok, thanks
