### ISSUE TITLE
'NumberKit' requires minimum platform version 12.0 for the iOS platform

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-sdk-swift#24]
### Description

When I tried to link hedera-sdk-swift package to my sample iOS project, I get this error:

`The package product 'NumberKit' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0`

If I uncomment iOS platform in Package.swift, error above disappears:

```
let package = Package(
    name: "Hedera",
    platforms: [
        .macOS(.v10_15)
        // .iOS(.v12),           <=== HERE
    ],
    …
)
```

Now I get the error reported in #22 (this one is closed but issue still exists).

### Steps to reproduce

1) Start Xcode
2) File > New > Project > iOS > App
    Product Name: XXX
    …
    Language: Swift
3) File > Add Packages
4) hedera-sdk-swift in Search Field + Add Package
5) Product > Build
    => build breaks ; see build output below

```
Prepare build
...
Build target Hedera with configuration Debug
error: The package product 'NumberKit' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0 (in target 'Hedera' from project 'Hedera')
error: Both 'macos-arm64' and 'macos-x86_64' represent two equivalent library definitions. (in target 'Hedera' from project 'Hedera')
...
Build failed    13/09/2022 23:29    0.1 seconds
```

### Additional context

[Build XXX_2022-09-13T23-29-18.txt](https://github.com/hashgraph/hedera-sdk-swift/files/9560980/Build.XXX_2022-09-13T23-29-18.txt)

### Hedera network

other

### Version

0.6.0

### Operating system

macOS

**Comment by mehcode** [comment]
Fixed for sure this time in https://github.com/hashgraph/hedera-sdk-swift/releases/tag/0.7.0
