### ISSUE TITLE
Go back over existing unit tests for transactions and queries and add `fromProtoBody` and `getSet<field>` tests

### ISSUE THREAD

**Issue by izik1** [hashgraph/hedera-sdk-swift#272]
The issues for these unit tests are closed, since, this is an improvement over other SDK's test suite rather than implementing those test suits

**Comment by RickyLB** [comment]
@izik1 Reminder: Adding tests to the issues mentioned in this PR https://github.com/hashgraph/hedera-sdk-swift/pull/219.
