### ISSUE TITLE
Both 'macos-arm64' and 'macos-x86_64' represent two equivalent library definitions (TAKE #2)

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-sdk-swift#28]
### Description

Issue #22 has been closed but issue still exists with current release of hedera-sdk-swift (0.6.0).

### Steps to reproduce

See issue #22.

### Hedera network

previewnet

### Version

v0.6.0

### Operating system

macOS

**Comment by mehcode** [comment]
Fixed in https://github.com/hashgraph/hedera-sdk-swift/releases/tag/0.7.0
