### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-sdk-swift#31]
### Description

What Happend
- Build but I have some compile errors. 

Expected Result
- Build complete without any compile error.

### Steps to reproduce

- cloned the repository with version 0.7.0
- Build with XCode. (I am using Xcode v 13.4.1 and MacBook Pro M1 with OSX v12.2.1(Monterey).
![p01](https://user-images.githubusercontent.com/32191478/200478040-3c068417-f04b-4087-a2e5-1e61b2fa07ba.png)
![p03](https://user-images.githubusercontent.com/32191478/200478044-a96a6af1-f661-4e2c-8f38-0567facb702e.png)
![p02](https://user-images.githubusercontent.com/32191478/200478055-c0560a12-1ded-419a-8e87-dd906ca79c7a.png)

### Hedera network

testnet

### Version

0.7.0

### Operating system

macOS

**Comment by SimiHunjan** [comment]
You need to add the package properly through xcodes swift package manager and not clone. cc: @mehcode

**Comment by soharang** [comment]
@SimiHunjan  Thanks for your replying.
But same compile errors are occurred when I use swift package manager.
![image](https://user-images.githubusercontent.com/32191478/202106218-5c34387c-b67a-46cb-86c1-44a4bdf13a9f.png)

I added the package in following screen.
![image](https://user-images.githubusercontent.com/32191478/202106438-31fd5e9b-d787-44c1-8b48-79bbab49c21a.png)

And added dependency as below.
![image](https://user-images.githubusercontent.com/32191478/202106620-75392b69-f009-41d5-9b3a-17a8591a89c6.png)

**Comment by ericleponner** [comment]
@soharang 
I did pretty much the same for my sample (iOS) program and Hedera module compiled and linked fine.
I used Xcode 14.1. What version of Xcode are you using ?

**Comment by soharang** [comment]
@ericleponner Thank you for your asking.
I am using Xcode v 13.4.1 and MacBook Pro M1 with OSX v12.2.1(Monterey).
And iOS deployment target of the project is 15.5.

**Comment by ericleponner** [comment]
hedera-sdk-swift readme says:
```
Swift v5.3+
MacOS v10.15+ (2019, Catalina)
iOS 12+ (2018)
```
Your specs seem to be ok. Strange …

**Comment by mehcode** [comment]
We have CI running the Swift tests over at https://github.com/hashgraph/hedera-sdk-rust/actions/runs/3465284263/jobs/5787866394 which is running MacOS v12. It doesn't state an explicit Swift version so I want to assume it's the same as what you would have on MacOS v12. 

I asked our Swift engineer to work on improving the CI today to test a set of explicit Swift versions and to copy the CI over on this repo as well.

**Comment by soharang** [comment]
@mehcode  @ericleponner 
Thanks for your supports.
If you want me to test with another environment, please let me know.

**Comment by mehcode** [comment]
We figured out that we accidentally introduced some code in 0.7 that will only work on Swift 5.7+. We've fixed that in the repo and we will get 0.9 out today.

**Comment by mehcode** [comment]
@soharang This should be fixed by v0.9.0.

**Comment by soharang** [comment]
@mehcode Thanks for your quick support.
Now I can get build successful with v0.9.0.
