### ISSUE TITLE
How to create Swift Transaction object from base64 encoded representation of TransactionBody?

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#333]
### Description

I'm using [dApp](https://wc.hgraph.app/) for [hedera_signTransaction](https://specs.walletconnect.com/2.0/blockchain-rpc/hedera-rpc#hedera_signtransaction) transaction and it send transactionBody (Base64 encoded string representation of TransactionBody) for sign request using wallet.
I'm using Mobile App with Swift Hedera SDK. Can you please suggest how to create Swift Transaction from base64 encoded representation of TransactionBody.

### Steps to reproduce

Create an object of Proto_TransactionBody from base64 encoded string and try to create Transaction object using Swift Hedera SDK

### Hedera network

testnet

### Version

v2.27.0

### Operating system

None

**Comment by RickyLB** [comment]
@nirmalpatidar123 The Hedera SDKs do not support base64 conversion to `TransactionBody`. It does convert bytes to `TransactionBody` though. I suggest converting base64 string to type `Data` (bytes) and passing it in to `Transaction.fromBytes()` within the dApp.

**Comment by SimiHunjan** [comment]
Please re-open if you have any additional comments.
