### ISSUE TITLE
Open TokenNftTransfer for initialization

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#334]
### Problem

I want to create an object of TokenNftTransfer but it shows below error

`TokenNftTransfer.init(tokenId: tokenId, sender: senderAccountId, receiver: receiverAccountId, serial:serialNo, isApproved: true)`

'TokenNftTransfer' initializer is inaccessible due to 'internal' protection level

### Solution

Add a public initializer

```
public init(tokenId: TokenId, sender: AccountId, receiver: AccountId, serial: UInt64, isApproved: Bool) {
        self.tokenId = tokenId
        self.sender = sender
        self.receiver = receiver
        self.serial = serial
        self.isApproved = isApproved
}
```

**Comment by RickyLB** [comment]
@nirmalpatidar123 Transferring NFTs is done through `TransferTransaction.nftTransfer()`. `TokenNftTransfer` object holds the metadata of that transfer.

https://github.com/hashgraph/hedera-sdk-swift/blob/6c57705dfc52fe1a7cdc373022f3e3faedb17143/Sources/Hedera/TransferTransaction.swift#L195-L201).
