### ISSUE TITLE
Add example: Add and remove NFT Allowances

### ISSUE THREAD

**Issue by RickyLB** [hashgraph/hedera-sdk-swift#385]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue

The Hedera SDK offers an example to demonstrate how to add and remove NFT allowances, which is a crucial process for controlling asset permissions. However, the complexity of the operations can make it difficult for developers to follow without a clear step-by-step breakdown.

## Solution 
This example in the Java SDK showcases the process of managing NFT allowances, including creating NFTs, approving and revoking permissions, and transferring tokens using the Hedera SDK. By following these steps, developers can implement allowance functionality efficiently. [NftAddRemoveAllowancesExamples.java](https://github.com/hashgraph/hedera-sdk-java/blob/main/examples/src/main/java/com/hedera/hashgraph/sdk/examples/NftAddRemoveAllowancesExample.java)

We need to provide such example for the swift sdk, too.

## Implementation
1. Set up the SDK client with the necessary operator account and key.
2. Create a unique NFT and retrieve the associated token ID.
3. Mint NFTs by attaching metadata to each unique token serial number.
4. Generate spender and receiver accounts with their respective keys.
5. Associate the spender and receiver accounts with the NFT token.
6. Grant allowance for specific NFT serials to the spender account.
7. Execute an NFT transfer using the approved allowance on behalf of the spender.
8. Revoke the allowance for specific NFT serial numbers.
9. Attempt another transfer after revocation to confirm the permission removal.
10. Clean up resources by deleting the tokens and accounts used in the process.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by aazam-gh** [comment]
I would like to work on this!

**Comment by aazam-gh** [comment]
Sorry, will have to unassign on this issue as I can't obtain a mac atm

**Comment by b-l-u-e** [comment]
Please assign me on this issue

**Comment by Atharva1723** [comment]
Can I work on this issue?

**Comment by b-l-u-e** [comment]
Please unassign me from this issue 
The Mac that am using it’s not meeting the requirements for this project..I tried setting it up but kept getting errors
I was looking forward to the project..unfortunately I won’t be able to contribute @hendrikebbers

**Comment by b-l-u-e** [comment]
Thank you @hendrikebbers
