### ISSUE TITLE
Ambiguous use of 'init(_:)'

### ISSUE THREAD

**Issue by ramesh-aureus** [hashgraph/hedera-sdk-swift#389]
### Description

I am getting alot of these kinds of issues.. 

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/SolidityAddress.swift:39:24

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/StakingInfo.swift:71:27

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/SystemDeleteTransaction.swift:50:52

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Timestamp.swift:19:33

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Timestamp.swift:46:18

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Timestamp.swift:52:35

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Timestamp.swift:85:27

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Token/NftId.swift:85:20

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Token/TokenAllowance.swift:23:20

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountBalance.swift:117:28

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountCreateTransaction.swift:69:32

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountCreateTransaction.swift:286:35

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountId.swift:139:16

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountId.swift:140:16

Swift Compiler Error (Xcode): Type of expression is ambiguous without a type annotation
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountInfo.swift:180:9

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountInfo.swift:213:28

Swift Compiler Error (Xcode): Ambiguous use of 'init(_:)'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountUpdateTransaction.swift:47:23

Swift Compiler Error (Xcode): Ambiguous use of 'max'
/Users/darkness/Library/Developer/Xcode/DerivedData/Runner-dvtigcgisdkkghcsrzomqcuqdlmc/SourcePackages/checkouts/hedera-sdk-swift/Sources/Hedera/Account/AccountUpdateTransaction.swift:277:30

### Steps to reproduce

1) Add thew swift package
2) run the app

### Hedera network

mainnet

### Version

latest

### Operating system

macOS

**Comment by SimiHunjan** [comment]
@ramesh-aureus are you still observing these issues?

**Comment by RickyLB** [comment]
@ramesh-aureus Currently, I'm not able to reproduce this error.

**Comment by ramesh-aureus** [comment]
Thank you guys for the concern.. The issues has been resolved in one the the previous PRs merge.
