### ISSUE TITLE
Unable to create NFT with Custom Fee

### ISSUE THREAD

**Issue by nirmalpatidar123** [hashgraph/hedera-sdk-swift#39]
### Description

When I tried to create NFT with Custom fee with no denomination token id then I receive below error
**failed to parse a request from JSON: missing field `denominatingTokenId` at line 1 column 951**

But when I added any random token id then transaction execution was successful

### Steps to reproduce

When I tried using below custom fee I got the error
```
let fixedFee = FixedFee(amount: 1000, denominatingTokenId: nil, feeCollectorAccountId: collectorID, allCollectorsAreExempt: true)
let fallbackFee = FixedFee(amount: 200, denominatingTokenId: nil, feeCollectorAccountId: collectorID, allCollectorsAreExempt: true)
let royaltyFee = RoyaltyFee(numerator: 1, denominator: 50, fallbackFee: fallbackFee, feeCollectorAccountId: collectorID, allCollectorsAreExempt: true)
```

### Hedera network

testnet

### Version

v0.14.0

### Operating system

macOS

**Comment by izik1** [comment]
Hi, I've created a PR that will fix this, should be out with the next release next week.
