### ISSUE TITLE
memo field does not exist for Transaction

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-sdk-swift#40]
### Description

`TransferTransaction` doesn't have a function for setting memo.

### Steps to reproduce

Try to write code as below additional context with memo.

### Additional context

```
let response = try await TransferTransaction()
                    .hbarTransfer(AccountId.fromString(coinWallet.getWalletAddress()), sendAmount * -1)
                    .hbarTransfer(AccountId.fromString(toAddress), sendAmount)
                    .memo("memo test") // <- cannot set memo for now
                    .execute(client)
```

### Hedera network

mainnet

### Version

0.14.0

### Operating system

macOS

**Comment by izik1** [comment]
Hi! Thanks for reaching out

This is a known limitation currently, I can prioritize it getting added before the next release
