### ISSUE TITLE
Cannot compile due to unsafe build flag

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-sdk-swift#43]
### Description

With sdk v0.16.0, there is a problem when compiling.

It always returns following error message.
"the target 'Hedera' in product 'Hedera' contains unsafe build flags."

![Screenshot 2023-04-10 at 2 36 52 PM](https://user-images.githubusercontent.com/32191478/230833650-09d6d8e9-8ffb-4517-be2c-d1f28d64a73e.png)

### Steps to reproduce
XCode 14.2
1. Import Hedera swift sdk ver 0.16.0 on my package.
2. Try to build with it.

### Additional context

```
.package(name: "hedera-sdk-swift", url: "https://github.com/hashgraph/hedera-sdk-swift.git", .exact("0.16.0")),
```

### Hedera network

mainnet

### Version

v0.16.0

### Operating system

macOS

**Comment by izik1** [comment]
Hi! Terribly sorry about that, the `unsafeFlags` in question are:
```
            swiftSettings: [
                .unsafeFlags(["-Xfrontend", "-warn-concurrency", "-Xfrontend", "-enable-actor-data-race-checks"])
            ]
```
Which I would like to have enabled locally, I'll see what I can do about it for the next release.
